default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: faye_chat_demo_development

test:
  <<: *default
  database: faye_chat_demo_test

staging:
  <<: *default
  database: faye_chat_demo_staging

production:
  <<: *default
  database: faye_chat_demo_production
